In [2]:
age=22
print(type(age))
name="Rashi"
is_student=True
print(type(is_student))

<class 'int'>
<class 'bool'>

In [3]:
age=20
if age>=18:
  print("Adult")

Adult

In [5]:
age=16
if age>=18:
  print("Eligible")
else:
   print("Not Eligible")

Not Eligible

In [6]:
marks=72
if marks>=90:
  print("A+")
elif marks>=75:
  print("A")
elif marks >=60:
 print("B")
elif marks >=50:
  print("C")
else:
 print("Fail")

B

In [7]:
age=25
fare=80
if age >=18 and fare >=50:
  print("Condition Satisfied")

Condition Satisfied

In [10]:
age=25
survived=1
if age>=18:
  if survived ==1:
    print("Adult survivor")

Adult survivor

**LISTS**

ordered
indexed
mutable
can contain duplicate values
**uses square brackets[]**

In [11]:
my_list=[]
my_list

[]

[]

In [13]:
ages =[22,38,36,35,35]
names=["Asha","Sachin","Utkarsh"]
mixed=[10,"Python",3.5,True]

In [14]:
print(ages)
print(names)
print(mixed)

[22, 38, 36, 35, 35]
['Asha', 'Sachin', 'Utkarsh']
[10, 'Python', 3.5, True]

In [21]:
print(ages[0])
print(ages[-1])
print(names[-1])
print(ages[1:4])
print(ages[1:])
print(ages[:2])
print(ages[::2])
print(mixed[::2])

22
35
Utkarsh
[38, 36, 35]
[38, 36, 35, 35]
[22, 38]
[22, 36, 35]
[10, 3.5]

In [32]:
print(ages)
ages[2]=27
print(ages)

[22, 38, 27, 35, 35]
[22, 38, 27, 35, 35]

In [27]:
print(names)
names.append("Tina")
print(names)

['Asha', 'Sachin', 'Utkarsh']
['Asha', 'Sachin', 'Utkarsh', 'Tina']

In [33]:
#insert
names=["Asha","Sachin","Utkarsh"]
names.insert(1,"Rashi")
print(names)
names.insert(0,"yashi")
print(names)

['Asha', 'Rashi', 'Sachin', 'Utkarsh']
['yashi', 'Asha', 'Rashi', 'Sachin', 'Utkarsh']

In [64]:
print(names)
names.extend(["Vansh","Vaibhav"])

['Asha', 'Sachin']

In [65]:
print(names)

['Asha', 'Sachin', 'Vansh', 'Vaibhav']

In [34]:
#removing/deleting items
names.remove("Asha")
print(names)

['yashi', 'Rashi', 'Sachin', 'Utkarsh']

In [39]:
removed=names.pop(2)
print(removed)
print(names)

Utkarsh
['Asha', 'Sachin']

In [68]:
print(ages)
del ages[1]
print(ages)

[22, 35, 35]
[22, 35]

In [41]:
numbers=[10,20,30]
numbers.clear()
print(numbers)

[]

In [42]:
numbers=[40,10,30,20,10]
print(len(numbers))

5

In [44]:
print(numbers.count(10))

2

In [45]:
print(numbers)
print(numbers.index(30))

[40, 10, 30, 20, 10]
2

In [46]:
print(numbers)
print(10 in numbers)

[40, 10, 30, 20, 10]
True

In [47]:
print(50 in numbers)

False

In [48]:
print(max(numbers))

40

In [49]:
print(min(numbers))

10

In [50]:
print(sum(numbers))

110

In [51]:
numbers.sort()

In [52]:
print(numbers)

[10, 10, 20, 30, 40]

In [53]:
numbers.reverse()
print(numbers)

[40, 30, 20, 10, 10]

In [55]:
students=[
    ["Tanvi",21,"CSE"],
    ["Utkarsh",22,"CSE"],
    ["Upman",20,"ECE"]
]

In [56]:
print(students[0])

['Tanvi', 21, 'CSE']

In [57]:
print(students[0][0])

Tanvi

In [58]:
print(students[2][2])

ECE

In [59]:
students[0][1]=22
print(students)

[['Tanvi', 22, 'CSE'], ['Utkarsh', 22, 'CSE'], ['Upman', 20, 'ECE']]

In [60]:
students.append(["Sachin",23,"IT"])

In [61]:
print(students)

[['Tanvi', 22, 'CSE'], ['Utkarsh', 22, 'CSE'], ['Upman', 20, 'ECE'], ['Sachin', 23, 'IT']]

In [62]:
for student in students:
  print(student)

['Tanvi', 22, 'CSE']
['Utkarsh', 22, 'CSE']
['Upman', 20, 'ECE']
['Sachin', 23, 'IT']

In [63]:
for value in student:
    print(value)

Sachin
23
IT

In [67]:
#combining lists with conditions
marks=[35,62,81,45,90]
for mark in marks:
  if mark >=50:
    print(mark,"Pass")
  else:
    print(mark,"Fail")

35 Fail
62 Pass
81 Pass
45 Fail
90 Pass

**MAKE A DATAFRAME**

In [69]:
import pandas as pd
data={
    "Customer":["A1","A2","A3","A4","A5"],
    "Age":[22,35,28,40,55],
    "City":["Delhi","Mathura","Lucknow","Varanasi","Agra"],
    "Amount":[1200,3500,7000,4200,9500],
    "Rating":[4.5,3.5,2,4,5]
}
df=pd.DataFrame(data)
print(df)

  Customer  Age      City  Amount  Rating
0       A1   22     Delhi    1200     4.5
1       A2   35   Mathura    3500     3.5
2       A3   28   Lucknow    7000     2.0
3       A4   40  Varanasi    4200     4.0
4       A5   55      Agra    9500     5.0

In [70]:
df.loc[0:3,["Customer","City","Amount"]]

  Customer      City  Amount
0       A1     Delhi    1200
1       A2   Mathura    3500
2       A3   Lucknow    7000
3       A4  Varanasi    4200

In [71]:
df.loc[df["Amount"]>5000,["Customer","Amount"]]

  Customer  Amount
2       A3    7000
4       A5    9500

In [72]:
#First 5 rows and first 3 columns
df.iloc[0:5,0:3]

  Customer  Age      City
0       A1   22     Delhi
1       A2   35   Mathura
2       A3   28   Lucknow
3       A4   40  Varanasi
4       A5   55      Agra